### PR TITLE
added uniclose draft

### PR DESCRIPTION
**Pull request by pm47**
This is something I started a while ago, the goal was to describe how a unilateral close should properly be handled. One could consider these are "internals" and need not be specified here, but I think this definitely is one of the most crucial parts of a Lightning node.

That said I am not sure it belongs to its own BOLT, or maybe it should be an addition to a more general one about how the commitment transaction should be formatted (exact specification of scripts, ordering of outputs, etc.)

What do you think?

### CODE REVIEW

**Comment by rustyrussell** [comment]
Pierre-Marie Padiou <notifications@github.com> writes:
> This is something I started a while ago, the goal was to describe how a unilateral close should properly be handled. One could consider these are "internals" and need not be specified here, but I think this definitely is one of the most crucial parts of a Lightning node.
>
> That said I am not sure it belongs to its own BOLT, or maybe it should be an addition to a more general one about how the commitment transaction should be formatted (exact specification of scripts, ordering of outputs, etc.)
>
> What do you think?

Damn, you beat me to it!

I was just thinking about this yesterday.  I believe it's worth
dedicating an entire informational BOLT on this, because as you say,
it's crucial (and sometimes criticial!).

(I also don't like the state machine I have; it's unnecessarily complex,
so writing a spec which I can quote and follow makes sense).

I will take this and turn it into BOLT #3 this week, I think!

Thanks!
Rusty.

**Comment by pm47** [comment]
;-) I did this in february, as a technical blog post to better explain to what extent LN preserved bitcoin trustless properties, but it's largely incomplete.

I would be happy to turn it into a proper BOLT myself if that helps, please let me know what you prefer.

Have a good WE,
Pierre

**Comment by rustyrussell** [comment]
Pierre-Marie Padiou <notifications@github.com> writes:
> ;-) I did this in february, as a technical blog post to better explain to what extent LN preserved bitcoin trustless properties, but it's largely incomplete.
>
> I would be happy to turn it into a proper BOLT myself if that helps, please let me know what you prefer.

Here's my first cut:

https://github.com/rustyrussell/lightning/blob/onchain-spec/early-drafts/uniclose.md

I think it covers everything; I'm about to reimplement based on that, so
I might have corrections as I go...

Thanks!
Rusty.

**Comment by pm47** [comment]
Is it a director's cut or a complete hollywood remake? ;-) Just kidding, but it is interesting that you focus on a single channel while I was more interested in the relaying of information between the downstream/upstream channels involved in the same payment when a failure occurs somewhere. It is like if you are looking more at the bidir channel aspect and I am looking more at the conditional payment aspect. But at the end of the day it is equivalent and I also think this covers everything.

I spotted a few typos along the way (see: [typos_patch.txt](https://github.com/rustyrussell/lightning/files/247192/typos_patch.txt))

Cheers,
Pierre

**Comment by rustyrussell** [comment]
Pierre-Marie Padiou <notifications@github.com> writes:
> Is it a director's cut or a complete hollywood remake? ;-)

I know, sorry about that.  I got carried away a bit I think, and it lost
some of the flavour.

We're going to need a roadmap document eventually which explains what
all the pieces are, and that should be much more chatty.

> Just kidding, but it is interesting that you focus on a single channel while I was more interested in the relaying of information between the downstream/upstream channels involved in the same payment when a failure occurs somewhere. It is like if you are looking more at the bidir channel aspect and I am looking more at the conditional payment aspect. But at the end of the day it is equivalent and I also think this covers everything.

Yes, I think it's because my implementation is still only point-to-point
so that's where my brain is.

> I spotted a few typos along the way (see: [typos_patch.txt](https://github.com/rustyrussell/lightning/files/247192/typos_patch.txt))

Thanks, applied!

Cheers,
Rusty.

**Comment by pm47** [comment]
No problem! I guess this PR can be closed now

**Pull request closed without merging**
